src/components/Header/Header.style.ts, src/components/Sidebar/Sidebar.style.ts, src/components/Sidebar/Sidebar.types.ts, src/components/Sidebar/index.tsx, src/components/SidebarButton/SidebarButton.style.ts, src/components/SidebarButton/SidebarButton.types.ts, src/components/SidebarButton/index.tsx, src/pages/CafeSearchPage/CafeSearchPage.tsx, src/pages/MainPage/MainPage.style.ts, src/pages/MainPage/MainPage.tsx, src/pages/MyPage/MyPage.tsx, src/pages/StudySearchPage/StudySearchPage.tsx, src/routes/index.tsx
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
사이드바 구현
버튼 hover, active 시  색은 임시로 설정해두었습니다. 디자이너 님과 상의해서 추후에 수정하면 될 것 같아요!
close #issue8
=> ✨ feat: 사이드바 구현

src/pages/CafeSearchPage/CafeSearchPage.tsx, src/pages/CafeSearchResultPage/CafeSearchResultPage.style.ts, src/pages/CafeSearchResultPage/CafeSearchResultPage.tsx, src/routes/index.tsx
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
카페 검색 결과 타이틀 레이아웃 구현
- 카페 검색 결과 페이지 라우터 설정
- 카페 검색 결과 페이지 타이틀 레이아웃 구현
close #15
=> ✨Feat/cafe search result

src/pages/CafeMeetingSearchResultPage/CafeMeetingSearchResultPage.hooks.ts, src/pages/CafeMeetingSearchResultPage/CafeMeetingSearchResultPage.style.ts, src/pages/CafeMeetingSearchResultPage/CafeMeetingSearchResultPage.tsx, src/pages/CafeMeetingSearchResultPage/CafeMeetingSearchResultPage.type.ts, src/routes/index.tsx
- 레이아웃 작업
레이아웃 작업했습니다.
close #27
=> ✨feature/cafe_meeting_search_result

.gitignore, package-lock.json, package.json, src/pages/CafeCreateRecruitmentPage/CafeCreateRecruitmentPage.hooks.ts, src/pages/CafeCreateRecruitmentPage/CafeCreateRecruitmentPage.tsx, src/pages/CafeCreateRecruitmentPage/CafeCreateRecruitmentPage.type.ts
카공 모집 글 생성 api 작업했습니다.
cafeId는 임시로 하드코딩했습니다.
close #issue 32
=> ✨ Feature/create recruitment api

package-lock.json, package.json, src/pages/CafeSearchPage/CafeSearchPage.style.ts, src/pages/CafeSearchPage/CafeSearchPage.tsx, src/pages/CafeSearchResultPage/CafeSearchResultPage.hooks.ts, src/pages/CafeSearchResultPage/CafeSearchResultPage.style.ts, src/pages/CafeSearchResultPage/CafeSearchResultPage.tsx, src/pages/CafeSearchResultPage/CafeSearchResultPage.type.ts, src/routes/index.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
api 연동 작업했습니다.
close #53
=> ✨ Feature/ap icafe search result

src/pages/CafeMeetingSearchPage/CafeMeetingSearchPage.tsx, src/pages/CafeMeetingSearchResultPage/CafeMeetingSearchResultPage.hooks.ts, src/pages/CafeMeetingSearchResultPage/CafeMeetingSearchResultPage.tsx, src/pages/CafeMeetingSearchResultPage/CafeMeetingSearchResultPage.type.ts, src/routes/index.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
카공 검색 목록 api 연동 작업함
close #57
=> ✨ Feature/api cafe study search result

src/pages/CafeMeetingSearchPage/CafeMeetingSearchPage.tsx, src/pages/CafeMeetingSearchResultPage/CafeMeetingSearchResultPage.tsx, src/pages/CafeSearchPage/CafeSearchPage.tsx, src/pages/CafeSearchResultPage/CafeSearchResultPage.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
재검색 기능 수정함
close #59
=> ✨ feature/cafeReSearch

src/pages/CafeCreateRecruitmentPage/CafeCreateRecruitmentPage.hooks.ts, src/pages/CafeCreateRecruitmentPage/CafeCreateRecruitmentPage.tsx, src/pages/CafeCreateRecruitmentPage/CafeCreateRecruitmentPage.type.ts, src/pages/CafeSearchResultPage/CafeSearchResultPage.style.ts, src/pages/CafeSearchResultPage/CafeSearchResultPage.tsx, src/routes/index.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
-  [x] 카페 이미지 제거
close #61
=> ✨ Feature/cafe

public/index.html, src/components/Kakao/Kakao.style.ts, src/components/Kakao/index.tsx, src/pages/CafeMeetingSearchResultPage/CafeMeetingSearchResultPage.tsx, src/pages/CafeSearchResultPage/CafeSearchResultPage.tsx, src/routes/index.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
카카오 지도 api 연동 작업함
close #63
=> ✨ Feature/api map

src/pages/CafeInfoPage/CafeInfo.hooks.ts, src/pages/CafeInfoPage/CafeInfo.types.ts, src/pages/CafeInfoPage/CafeInfoPage.style.ts, src/pages/CafeInfoPage/CafeInfoPage.tsx, src/pages/CafeSearchResultPage/CafeSearchResultPage.tsx, src/routes/index.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
카페 상세 api 연동
=> ✨Feature/cafe info api

src/components/StudyModal/index.tsx, src/pages/CafeInfoPage/CafeInfoPage.tsx, src/pages/CafeMeetingInfoPage/CafeMeetingInfoPage.hook.ts, src/pages/CafeMeetingInfoPage/CafeMeetingInfoPage.style.ts, src/pages/CafeMeetingInfoPage/CafeMeetingInfoPage.tsx, src/pages/CafeMeetingInfoPage/CafeMeetingInfoPage.type.ts, src/pages/MyPage/MyPage.hooks.ts, src/routes/index.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
=> ✨Feature/cafe meeting info api

src/pages/CafeInfoPage/CafeInfoPage.style.ts, src/pages/CafeInfoPage/CafeInfoPage.tsx, src/pages/CafeMeetingInfoPage/CafeMeetingInfoPage.hook.ts, src/pages/CafeMeetingInfoPage/CafeMeetingInfoPage.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #75
=> ✨Feature/join cafe meeting

src/pages/AttendancePage/AttendancePage.hook.ts, src/pages/AttendancePage/AttendancePage.tsx, src/pages/AttendancePage/AttendancePage.type.ts, src/routes/index.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
출석체크 API 연동
close #72
=> ✨ Feature/api attendance check

src/components/QnaEditModal/QnaEditModal.hooks.ts, src/components/QnaEditModal/QnaEditModal.style.ts, src/components/QnaEditModal/QnaEditModal.types.ts, src/components/QnaEditModal/index.tsx, src/pages/CafeInfoPage/CafeInfoPage.tsx, src/pages/CafeMeetingInfoPage/CafeMeetingInfoPage.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #78
=> ✨Feature/qna edit api

src/components/CafeSearchModal/CafeSearchModal.hook.ts, src/components/CafeSearchModal/CafeSearchModal.style.ts, src/components/CafeSearchModal/CafeSearchModal.types.ts, src/components/CafeSearchModal/index.tsx, src/pages/CafeCreateRecruitmentPage/CafeCreateRecruitmentPage.hooks.ts, src/pages/CafeCreateRecruitmentPage/CafeCreateRecruitmentPage.style.ts, src/pages/CafeCreateRecruitmentPage/CafeCreateRecruitmentPage.tsx, src/pages/CafeCreateRecruitmentPage/CafeCreateRecruitmentPage.type.ts, src/pages/CafeRecruitmentModifyPage/CafeRecruitmentModifyPage.hooks.ts, src/pages/CafeRecruitmentModifyPage/CafeRecruitmentModifyPage.style.ts, src/pages/CafeRecruitmentModifyPage/CafeRecruitmentModifyPage.tsx, src/pages/CafeRecruitmentModifyPage/CafeRecruitmentModifyPage.type.ts
- 기능 추가  
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #65
=> ✨ Feature/api cafe study meeting modify

src/pages/CafeMeetingSearchPage/CafeMeetingSearchPage.tsx, src/pages/CafeSearchPage/CafeSearchPage.tsx, src/pages/MyPage/MyPage.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #73
=> ✨Feature/authorization alert

src/components/ReviewModal/ReviewModal.hooks.ts, src/components/ReviewModal/ReviewModal.types.ts, src/pages/CafeInfoPage/CafeInfoPage.tsx, src/pages/CafeMeetingInfoPage/CafeMeetingInfoPage.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #83
=> 🐛Feature/api bug fix

src/pages/CafeCreateRecruitmentPage/CafeCreateRecruitmentPage.hooks.ts, src/pages/CafeCreateRecruitmentPage/CafeCreateRecruitmentPage.tsx, src/pages/CafeCreateRecruitmentPage/CafeCreateRecruitmentPage.type.ts, src/pages/CafeInfoPage/CafeInfoPage.tsx, src/pages/CafeMeetingInfoPage/CafeMeetingInfoPage.tsx, src/pages/CafeMeetingSearchResultPage/CafeMeetingSearchResultPage.tsx, src/pages/CafeSearchResultPage/CafeSearchResultPage.tsx, src/pages/WriteReviewPage/WriteReviewPage.tsx, src/routes/index.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
네이게이트 작업함
close #81
=> ✨Feature/navigate setting

src/pages/CafeRecruitmentModifyPage/CafeRecruitmentModifyPage.hooks.ts, src/pages/CafeRecruitmentModifyPage/CafeRecruitmentModifyPage.tsx, src/pages/CafeRecruitmentModifyPage/CafeRecruitmentModifyPage.type.ts
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #87
=> ✨ feature/nowMemberCount

src/components/CafeSearchModal/index.tsx, src/pages/AttendancePage/AttendancePage.tsx, src/pages/CafeCreateRecruitmentPage/CafeCreateRecruitmentPage.hooks.ts, src/pages/CafeCreateRecruitmentPage/CafeCreateRecruitmentPage.tsx, src/pages/CafeMeetingInfoPage/CafeMeetingInfoPage.hook.ts, src/pages/CafeMeetingSearchResultPage/CafeMeetingSearchResultPage.tsx, src/pages/CafeRecruitmentModifyPage/CafeRecruitmentModifyPage.hooks.ts, src/pages/CafeRecruitmentModifyPage/CafeRecruitmentModifyPage.tsx, src/pages/CafeSearchResultPage/CafeSearchResultPage.tsx, src/pages/Login/LoginState.tsx, src/pages/MyPage/MyPage.hooks.ts
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #89
=> ✨ Feature/access token

src/pages/TemporaryMain/TemporaryMain.tsx, src/routes/index.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #92
=> ✨ feature/route

src/components/CafeSearchModal/CafeSearchModal.hook.ts, src/components/CafeSearchModal/index.tsx, src/components/Header/Header.hooks.ts, src/components/Header/index.tsx, src/components/LoginModal/index.tsx, src/components/QnaEditModal/QnaEditModal.hooks.ts, src/components/RefreashModal/RefreashModal.hooks.ts, src/components/RefreashModal/RefreashModal.style.ts, src/components/RefreashModal/RefreashModal.types.ts, src/components/RefreashModal/index.tsx, src/components/ReviewModal/ReviewModal.hooks.ts, src/pages/AttendancePage/AttendancePage.tsx, src/pages/CafeCreateRecruitmentPage/CafeCreateRecruitmentPage.hooks.ts, src/pages/CafeInfoPage/CafeInfo.hooks.ts, src/pages/CafeMeetingInfoPage/CafeMeetingInfoPage.hook.ts, src/pages/CafeMeetingSearchPage/CafeMeetingSearchPage.tsx, src/pages/CafeMeetingSearchResultPage/CafeMeetingSearchResultPage.tsx, src/pages/CafeRecruitmentModifyPage/CafeRecruitmentModifyPage.hooks.ts, src/pages/CafeRecruitmentModifyPage/CafeRecruitmentModifyPage.tsx, src/pages/CafeSearchPage/CafeSearchPage.tsx, src/pages/CafeSearchResultPage/CafeSearchResultPage.tsx, src/pages/Login/LoginState.tsx, src/pages/MyPage/MyPage.hooks.ts, src/pages/MyPage/MyPage.tsx, src/routes/index.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #91
=> ✨Feature/reissuance

src/pages/CafeInfoPage/CafeInfo.hooks.ts, src/pages/CafeInfoPage/CafeInfo.types.ts, src/pages/CafeInfoPage/CafeInfoPage.style.ts, src/pages/CafeInfoPage/CafeInfoPage.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #95
=> ✨ Feature/add cafe meeting info

src/components/CafeSearchModal/index.tsx, src/components/Header/index.tsx, src/components/QnaEditModal/QnaEditModal.hooks.ts, src/components/RefreshModal/RefreshModal.hooks.ts, src/components/RefreshModal/RefreshModal.style.ts, src/components/RefreshModal/RefreshModal.types.ts, src/components/RefreshModal/index.tsx, src/components/ReviewModal/ReviewModal.hooks.ts, src/components/ReviewModal/index.tsx, src/pages/AttendancePage/AttendancePage.tsx, src/pages/CafeCreateRecruitmentPage/CafeCreateRecruitmentPage.hooks.ts, src/pages/CafeInfoPage/CafeInfo.hooks.ts, src/pages/CafeMeetingInfoPage/CafeMeetingInfoPage.hook.ts, src/pages/CafeMeetingSearchResultPage/CafeMeetingSearchResultPage.tsx, src/pages/CafeRecruitmentModifyPage/CafeRecruitmentModifyPage.hooks.ts, src/pages/CafeRecruitmentModifyPage/CafeRecruitmentModifyPage.tsx, src/pages/CafeSearchResultPage/CafeSearchResultPage.tsx, src/pages/Login/LoginState.tsx, src/pages/MyPage/MyPage.hooks.ts, src/pages/MyPageEditPage/MyPageEditPage.tsx, src/pages/WriteReviewPage/WriteReviewPage.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #issue번호
=> 🐛Fix/fix error

src/pages/CafeMeetingInfoPage/CafeMeetingInfoPage.hook.ts, src/pages/CafeMeetingInfoPage/CafeMeetingInfoPage.tsx, src/pages/CafeMeetingInfoPage/CafeMeetingInfoPage.type.ts
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #96
=> 🐛fix: fix_error2

src/components/CafeSearchModal/CafeSearchModal.style.ts, src/components/CafeSearchModal/index.tsx, src/components/Kakao/index.tsx, src/components/LoginModal/index.tsx, src/pages/CafeMeetingSearchPage/CafeMeetingSearchPage.style.ts, src/pages/CafeMeetingSearchPage/CafeMeetingSearchPage.tsx, src/pages/CafeRecruitmentModifyPage/CafeRecruitmentModifyPage.style.ts, src/pages/CafeRecruitmentModifyPage/CafeRecruitmentModifyPage.tsx, src/pages/CafeSearchPage/CafeSearchPage.style.ts
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #98
=> ✨ Feature/so layout

src/routes/index.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #102
=> 🐛 fix: HashRouter 변경 #102

package-lock.json, package.json, public/404.html, public/index.html, src/components/LoginModal/index.tsx, src/routes/index.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #104
=> 🐛 Feature/GitHub fourezerofour2

package.json
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #issue번호
=> 🐛 fix: 윈도우에 맞게 수정 #106

package.json
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #issue번호
=> 🐛 feat: 패키지 파일 수정 #108

src/routes/index.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #issue번호
=> ✨ feat: basename 수정 #113

src/routes/index.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #issue번호
=> 🐛 feature: 주석 추가 #115

src/routes/index.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #issue번호
=> 🐛 feat: basename 수정 #117

src/routes/index.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #issue번호
=> 🐛 feat: basename 경로 수정 #119

package.json, src/routes/index.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #issue번호
=> 🐛 feat: 홈페이지 경로 추가 #121

src/pages/MyPage/MyPage.tsx, src/routes/index.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #issue번호
=> 🐛 feat: 마이페이지 수정 #123

package.json
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #issue번호
=> 🐛 feat: 홈페이지 삭제 #125

src/routes/index.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #issue번호
=> 🐛 feat: HashRouter 변경 #127

src/routes/index.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #issue번호
=> 🐛 feat: BrowserRouter 설정 #129

package-lock.json, package.json
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #131
=> ✨chor: babel 설치 #131

src/routes/index.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #133
=> 🐛fix: BrowserRouter=>HashRouter

src/components/LoginModal/index.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #issue번호
=> 🐛fix: redirectUrl 수정

src/components/LoginModal/index.tsx, src/routes/index.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #137
=> 🐛 feat: HashRouter 삭제 #137

netlify.toml
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #issue번호
=> ✨ feat: netlify #141

src/pages/Login/LoginState.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #issue번호
=> ✨feat: console.log 추가 #143

src/components/Kakao/index.tsx, src/components/LoginModal/index.tsx, src/pages/CafeMeetingSearchResultPage/CafeMeetingSearchResultPage.hooks.ts, src/pages/CafeMeetingSearchResultPage/CafeMeetingSearchResultPage.style.ts, src/pages/CafeMeetingSearchResultPage/CafeMeetingSearchResultPage.tsx, src/pages/CafeMeetingSearchResultPage/CafeMeetingSearchResultPage.type.ts, src/pages/CafeSearchResultPage/CafeSearchResultPage.hooks.ts, src/pages/CafeSearchResultPage/CafeSearchResultPage.style.ts, src/pages/CafeSearchResultPage/CafeSearchResultPage.tsx, src/pages/CafeSearchResultPage/CafeSearchResultPage.type.ts
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #146
=> 🐛 Feature/kakao map api error

src/components/LoginModal/index.tsx, src/pages/CafeMeetingInfoPage/CafeMeetingInfoPage.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #149
=> ✨ Feature/attendance button

src/pages/CafeRecruitmentModifyPage/CafeRecruitmentModifyPage.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #151
=> ✨ feat: disabled 속성 추가 #151

src/pages/CafeInfoPage/CafeInfoPage.style.ts, src/pages/CafeInfoPage/CafeInfoPage.tsx, src/pages/CafeSearchPage/CafeSearchPage.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
- 비로그인 시에도 카페 검색이 가능하도록 수정
- 비로그인 시에 카페 기본 정보와 리뷰가 보이도록 수정 
close #issue번호
=> ✨feat: 카페 상세 정보 권한 수정

src/pages/AttendancePage/AttendancePage.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
출석체크 default 값 변경
close #158
=> ✨ feat: 출석체크 default 값 변경 #158

src/pages/CafeRecruitmentModifyPage/CafeRecruitmentModifyPage.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
2번 요청이 들어가는게 아니라 느린거였음
close #161
=> 🐛 fix: 비동기 삭제 #161

src/pages/CafeCreateRecruitmentPage/CafeCreateRecruitmentPage.hooks.ts, src/pages/CafeCreateRecruitmentPage/CafeCreateRecruitmentPage.tsx, src/pages/CafeCreateRecruitmentPage/CafeCreateRecruitmentPage.type.ts
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
Cannot deserialize value of type java.time.LocalDateTime from String "2024-09-26T24:00:00": Failed to deserialize java.time.LocalDateTime
close #164
=> 🐛 fix: 24->00 변경 #164

src/components/Header/Header.style.ts
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
스크롤시 지도때문에 헤더 안보임
close #166
=> 🐛 design: 지도 레이아웃 #166

src/components/LoginModal/index.tsx, src/pages/CafeMeetingSearchResultPage/CafeMeetingSearchResultPage.hooks.ts, src/pages/CafeMeetingSearchResultPage/CafeMeetingSearchResultPage.tsx, src/pages/CafeSearchResultPage/CafeSearchResultPage.hooks.ts
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 
- 코드 형태 개선 🎨
페이지네이션 작업함
close #170
=> 🐛 feat: 페이지네이션 변경 #170

src/components/CafeSearchModal/CafeSearchModal.hook.ts, src/components/CafeSearchModal/index.tsx, src/components/LoginModal/index.tsx, src/pages/CafeMeetingSearchPage/CafeMeetingSearchPage.tsx, src/pages/CafeSearchPage/CafeSearchPage.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #172
=> 🐛Feature/cafe re search pagenation

src/components/Pagination/Pagination.style.ts, src/components/Pagination/Pagination.type.ts, src/components/Pagination/index.tsx, src/components/ReviewModal/ReviewModal.hooks.ts, src/components/ReviewModal/ReviewModal.types.ts, src/components/ReviewModal/index.tsx, src/pages/CafeInfoPage/CafeInfoPage.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #162
=> ✨Feature/pagination

src/pages/CafeCreateRecruitmentPage/CafeCreateRecruitmentPage.hooks.ts, src/pages/CafeCreateRecruitmentPage/CafeCreateRecruitmentPage.tsx, src/pages/CafeRecruitmentModifyPage/CafeRecruitmentModifyPage.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
alert 메시지 수정
close #175
=> ✨Feature/alert

src/pages/CafeMeetingSearchResultPage/CafeMeetingSearchResultPage.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
url 수정
close #178
=> ✨feat: 카공 검색 url #178

src/components/DeleteModal/DeleteModal.hooks.ts, src/components/DeleteModal/DeleteModal.style.ts, src/components/DeleteModal/DeleteModal.types.ts, src/components/DeleteModal/index.tsx, src/components/ReviewModal/index.tsx, src/pages/CafeInfoPage/CafeInfoPage.tsx, src/pages/CafeMeetingInfoPage/CafeMeetingInfoPage.tsx, src/pages/MyPage/MyPage.tsx
- 기능 추가 ✨
- 기능 삭제 🔥
- 버그 수정 🐛
- 코드 형태 개선 🎨
close #160
=> ✨Feature/add feature qa
